---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
    env: local
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      env: local
  template:
    metadata:
      labels:
        app: nginx
        env: local
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: dev
spec:
  ports:
  - name: "80"
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    env: local
  type: ClusterIP
