---
apiVersion: v1
kind: Namespace
metadata:
  name: raccoon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raccoon
  namespace: raccoon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-pods
  namespace: raccoon
subjects:
- kind: ServiceAccount
  name: raccoon
  namespace: raccoon
roleRef:
  kind: ClusterRole
  name: manage-pods
  apiGroup: rbac.authorization.k8s.io
