image:
  repository: "ghcr.io/backmarket-oss/raccoon"
  tag: "latest"
  pullPolicy: "Always"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

datadog:
  enabled: false

# -- the namespace on which raccoon will collect pods
namespaceToRaccoon: default
dryRun: true
