apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "raccoon.fullname" . }}
  namespace: {{ .Values.namespaceToRaccoon }}
  labels:
    {{- include "raccoon.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "raccoon.fullname" . }}
  namespace: {{ .Values.namespaceToRaccoon }}
  labels:
    {{- include "raccoon.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "raccoon.fullname" . }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "raccoon.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "raccoon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "raccoon.labels" . | nindent 4 }}
